### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Guidanel**
Without these fixes HideIf does not work on:
- private serialized fields
- fields inside custom serialized classes/structs
- private fields from parent classes

### CODE REVIEW

**Comment by Stulk3** [comment]
These are really necessary features.
Thanks a lot for your attention and support!

**Comment by Guidanel** [comment]
Hello! I'm glad I could help, thanks for creating this repository in the
first place :)

**Comment by Stulk3** [comment]
I just updated the Readme file, indicating you in the Gratitude Heading. I also accidentally stumbled upon (I guess) your puzzle games. They look very interesting and catchy

**Comment by Guidanel** [comment]
That is very nice of you, thanks :)

**Pull request merged**
